apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: news-classifier-server
  namespace: default
  creationTimestamp: 
spec:
  name: news-classifier-server
  predictors:
  - name: default
    graph:
      name: news-classifier-server-processor
      endpoint:
        type: REST
      type: MODEL
      children: []
      parameters:
      - name: model_uri
        type: STRING
        value: "gs://news_classifier/model/"
    componentSpecs:
    - metadata:
        creationTimestamp: '2019-10-12T16:00:00Z'
      spec:
        containers:
        - image: axsauze/sklearn-server:0.1
          name: news-classifier-server-processor
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
        terminationGracePeriodSeconds: 1
    replicas: 1
    engineResources: {}
    svcOrchSpec: {}
    traffic: 100
    explainer:
      containerSpec:
        name: ''
        resources: {}
  annotations:
    seldon.io/engine-seldon-log-messages-externally: 'true'
status: {}
